# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftAndRightArrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Added', models.DateTimeField(auto_now=True)),
                ('HomePicLeftArrow', models.FileField(null=True, upload_to=b'HomeFront')),
                ('HomePicRighArrow', models.FileField(null=True, upload_to=b'HomeFront')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Last_Modified', models.DateTimeField(auto_now=True)),
                ('Photo_Album_Cover', models.FileField(upload_to=b'Photo/Cover')),
                ('Album_Url', models.CharField(max_length=200)),
            ],
        ),
    ]
