# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0021_auto_20160707_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbummodel',
            name='Photo_Album_Cover',
            field=models.FileField(upload_to=b'Photo/Cover'),
        ),
    ]
