# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0023_auto_20161230_0354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoAlbumModel',
        ),
    ]
