# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-21 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0024_delete_photoalbummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='Linkedin_API',
            field=models.TextField(default=datetime.datetime(2017, 5, 21, 19, 45, 18, 249865)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Music_API',
            field=models.TextField(default=datetime.datetime(2017, 5, 21, 19, 45, 26, 811105)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='YouTube_API',
            field=models.TextField(default=datetime.datetime(2017, 5, 21, 19, 45, 30, 803856)),
            preserve_default=False,
        ),
    ]
