# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0025_auto_20170521_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='HomeProfilePic',
            field=models.FileField(null=True, upload_to=b'HomeFront'),
        ),
    ]
