#!/bin/bash

rm -rf Freddie_Org
rm -rf Migrations
rm -rf django_project

mkdir Migrations

cp -rf About Migrations
cp -rf Comments Migrations
cp -rf PhotoAlbums Migrations
cp -rf Projects Migrations
cp -rf HomePage Migrations

if [ $# == 2 ] 
then
	echo "cp static and db.sqlite3"
	cp static Migrations
	cp db.sqlite3 Migrations
elif [ $# == 1 ]
then
	echo "cp static"
	cp static Migrations
fi

cp -rf templates Migrations

mkdir django_project
cp freddie_org/urls.py django_project
cp freddie_org/settings.py django_project

mkdir Freddie_Org
mv Migrations Freddie_Org
mv django_project Freddie_Org
cp migrate_Data Freddie_Org
