# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0026_homemodel_homeprofilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='HomeBGP',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='title',
        ),
    ]
