# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('Date_Added', models.DateTimeField(auto_now=True)),
                ('HomeLogo', models.FileField(upload_to='AboutFront')),
                ('HomeVideo', models.FileField(upload_to='AboutFront')),
                ('HomeBGP', models.FileField(null=True, upload_to='AboutFront')),
            ],
        ),
    ]
