# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_aboutsecondtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='Photo_Album_Cover',
            new_name='Top_Photo',
        ),
        migrations.AddField(
            model_name='aboutsecondtext',
            name='Second_Left',
            field=models.FileField(default=1, upload_to='About/Second'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsecondtext',
            name='Second_Right',
            field=models.FileField(default=1, upload_to='About/Second'),
            preserve_default=False,
        ),
    ]
