# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='HomeBGP',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='HomeLogo',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='HomeVideo',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Last_Modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 6, 14, 13, 46, 345999)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Photo_Album_Cover',
            field=models.FileField(default=datetime.datetime(2017, 2, 6, 14, 13, 52, 646926), upload_to='About/Top'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='first_text',
            field=models.CharField(default=datetime.datetime(2017, 2, 6, 14, 14, 2, 844952), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='second_text',
            field=models.CharField(default=datetime.datetime(2017, 2, 6, 14, 14, 10, 197157), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='third_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Date_Added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
