# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_aboutforthcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFifthContactHorizontal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='About/Fifth/icons')),
                ('href', models.CharField(max_length=150)),
                ('alt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFifthContactQrAndTwoLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_Code', models.FileField(upload_to='About/Fifth')),
                ('first_text', models.CharField(max_length=150)),
                ('second_text', models.CharField(max_length=200)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Last_Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFifthContactVertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.CharField(max_length=200)),
            ],
        ),
    ]
